(() => {
  const $=s=>document.querySelector(s);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const api=(p,o={})=>window.HIOSAuth.api(p,o);
  const ask=t=>{const i=$('#chatInput');if(!i)return;i.value=t;$('#toggleCopilot')?.click();setTimeout(()=>i.focus(),40)};
  const head=(title,desc,primary,secondary='')=>`<section class="workspace-head"><div><p class="eyebrow">HI OS • HI MARKETING</p><h2>${esc(title)}</h2><p>${esc(desc)}</p></div><div class="workspace-head-actions">${secondary?`<button data-workspace-command="${esc(secondary)}">Assistant</button>`:''}${primary?`<button class="primary" data-workspace-command="${esc(primary)}">Commencer</button>`:''}</div></section>`;
  const kpis=items=>`<section class="workspace-kpis">${items.map(([v,l])=>`<div class="workspace-kpi"><strong>${esc(v)}</strong><span>${esc(l)}</span></div>`).join('')}</section>`;
  const empty=(title,text,cmd)=>`<div class="workspace-empty"><div><strong>${esc(title)}</strong><p>${esc(text)}</p><button data-workspace-command="${esc(cmd)}">Demander à HI Assistant</button></div></div>`;
  const bind=()=>document.querySelectorAll('[data-workspace-command]').forEach(b=>b.onclick=()=>ask(b.dataset.workspaceCommand));

  async function render(key,m){
    const c=$('#content');c.innerHTML='<section class="workspace-empty"><div><strong>Chargement…</strong><p>HI OS prépare les données utiles.</p></div></section>';
    try{
      const [dash,health,jobs]=await Promise.all([
        api('/api/admin/dashboard').catch(()=>({clients:0,missions:0,applications:0,interviews:0,agentRuns:0})),
        fetch('/api/bootstrap-status',{credentials:'same-origin'}).then(r=>r.json()).catch(()=>({})),
        api('/api/admin/job-missions').catch(()=>({items:[]}))
      ]);
      const html=key==='crm'?clients(dash,jobs):key==='hunter'?prospecting(dash):key==='web'?projects(dash):key==='designer'?content(dash):key==='automation'?agents(dash,health):key==='analytics'?calendar(dash):key==='proposal'?documents(dash):key==='knowledge'?settings(dash,health):fallback(m,dash);
      c.innerHTML=`<section class="workspace-shell">${html}</section>`;bind();
    }catch(e){c.innerHTML=`<section class="workspace-shell">${head(m.name,m.desc,'Aide-moi à configurer ce module.')}<div class="workspace-note">Impossible de charger les données pour le moment : ${esc(e.message)}</div></section>`;bind();}
  }

  function clients(d,j){
    const rows=(j.items||[]).slice(0,8).map(x=>`<div class="workspace-row"><div><strong>${esc(x.client_name)}</strong><small>${esc(x.client_email||'')} • ${esc(x.title)}</small></div><span class="tag">${esc(x.status)}</span></div>`).join('');
    return `${head('Clients','Toutes les relations commerciales et missions clients au même endroit.','Ajoute un nouveau client à HI OS et prépare sa fiche.','Montre-moi les clients qui demandent une action aujourd’hui.')}${kpis([[d.clients,'Clients actifs'],[d.missions,'Missions actives'],[d.applications,'Candidatures'],[d.interviews,'Entretiens']])}<div class="workspace-grid"><article class="workspace-card"><div class="workspace-toolbar"><div><h3>Répertoire clients</h3><p class="sub">Données réelles actuellement disponibles dans HI OS.</p></div><input placeholder="Rechercher un client…" disabled></div>${rows?`<div class="workspace-list">${rows}</div>`:empty('Aucun client exploitable','Crée une première fiche client pour commencer le suivi commercial.','Crée un nouveau client pour HI MARKETING.')}</article><aside class="workspace-card"><h3>Prochaine action</h3><p class="sub">HI OS te remonte uniquement ce qui mérite ton attention.</p><div class="workspace-note" style="margin-top:14px">Les fiches CRM complètes seront alimentées par les missions, la prospection et les échanges clients. Aucune donnée fictive n’est affichée.</div></aside></div>`;
  }

  function prospecting(d){
    return `${head('Prospection','Un pipeline simple pour trouver, qualifier et convertir les entreprises ciblées.','Trouve 10 prospects qualifiés pour HI MARKETING et prépare les approches.','Analyse ma prospection et dis-moi quoi prioriser.')}${kpis([[d.clients,'Clients'],[d.agentRuns,'Runs agents / 24h'],[0,'Prospects à qualifier'],[0,'RDV commerciaux']])}<article class="workspace-card"><div class="workspace-toolbar"><div><h3>Pipeline commercial</h3><p class="sub">Nouveau → Qualifié → Contacté → Réponse.</p></div><button data-workspace-command="Lance Contract Hunter pour rechercher de nouveaux prospects pertinents.">Lancer Contract Hunter</button></div><div class="pipeline"><div class="pipeline-col"><h4>Nouveaux <span class="pipeline-count">0</span></h4></div><div class="pipeline-col"><h4>Qualifiés <span class="pipeline-count">0</span></h4></div><div class="pipeline-col"><h4>Contactés <span class="pipeline-count">0</span></h4></div><div class="pipeline-col"><h4>Réponses <span class="pipeline-count">0</span></h4></div></div><div class="workspace-note" style="margin-top:12px">Le pipeline n’invente aucune société. Les colonnes se rempliront uniquement avec les prospects réellement trouvés et enregistrés.</div></article>`;
  }

  function projects(d){
    return `${head('Projets','Sites, applications, automatisations et livrables pilotés depuis un seul endroit.','Crée un nouveau projet HI MARKETING et définis les premières tâches.','Fais le point sur tous mes projets en cours.')}${kpis([[d.missions,'Missions actives'],[0,'Projets ouverts'],[0,'Tâches en retard'],[0,'Livraisons cette semaine']])}<div class="workspace-grid"><article class="workspace-card"><h3>Projets en cours</h3><p class="sub">Les projets techniques et marketing apparaîtront ici dès leur création.</p><div style="margin-top:14px">${empty('Aucun projet structuré','Crée le premier projet pour activer les tâches, jalons et suivi de livraison.','Crée un projet HI MARKETING avec objectifs, livrables et échéances.')}</div></article><aside class="workspace-card"><h3>Flux recommandé</h3><div class="workspace-list" style="margin-top:12px"><div class="workspace-row"><div><strong>1. Cadrage</strong><small>Objectif, client, portée, échéance.</small></div></div><div class="workspace-row"><div><strong>2. Production</strong><small>Tâches, responsables, fichiers.</small></div></div><div class="workspace-row"><div><strong>3. QA</strong><small>Contrôle avant livraison.</small></div></div><div class="workspace-row"><div><strong>4. Livraison</strong><small>Validation et archivage.</small></div></div></div></aside></div>`;
  }

  function content(d){
    return `${head('Contenus','Studio central pour les affiches, vidéos, publications et campagnes de HI MARKETING.','Prépare 3 contenus pour HI MARKETING avec angle, format et texte.','Fais un audit du contenu à produire cette semaine.')}${kpis([[0,'À produire'],[0,'En validation'],[0,'Programmés'],[0,'Publiés']])}<div class="workspace-grid"><article class="workspace-card"><h3>Studio de production</h3><p class="sub">Brief → Création → Validation → Publication.</p><div style="margin-top:14px">${empty('Aucun contenu dans la file','Lance un brief depuis HI Assistant pour créer la première tâche de contenu.','Master Designer, crée le prochain contenu prioritaire pour HI MARKETING.')}</div></article><aside class="workspace-card"><h3>Formats</h3><div class="doc-grid" style="grid-template-columns:1fr 1fr;margin-top:12px"><div class="doc-card"><strong>Affiche</strong><small>Social, campagne, promo</small></div><div class="doc-card"><strong>Vidéo</strong><small>Reel, TikTok, démo</small></div><div class="doc-card"><strong>Carrousel</strong><small>LinkedIn / Instagram</small></div><div class="doc-card"><strong>Texte</strong><small>Post, légende, script</small></div></div></aside></div>`;
  }

  function agents(d,h){
    const list=[['HI Orchestrator','Route les missions vers les bons agents.','A1'],['Contract Hunter','Recherche et qualifie des prospects.','A2'],['CRM Agent','Structure les relations commerciales.','A2'],['Master Designer','Crée les directions visuelles et contenus.','A2'],['Web Agent','Construit et maintient les produits web.','A2'],['QA Agent','Vérifie la qualité avant livraison.','A2'],['Inbox Agent','Trie les messages et priorités.','A2'],['Job Search Factory','Pilote les recherches d’emploi clients.','A2']];
    return `${head('IA & Assistants','Tous les agents spécialisés de HI OS, avec leurs rôles et niveaux d’autonomie.','Montre-moi les tâches que les agents peuvent exécuter aujourd’hui.','Fais un diagnostic de tous les agents HI OS.')}${kpis([[d.agentRuns,'Exécutions / 24h'],[h.aiConfigured?'Prête':'Limitée','IA'],[h.gmailConfigured?'Prêt':'À configurer','Gmail OAuth'],[h.tenantIsolation?'Strict':'À vérifier','Isolation']])}<article class="workspace-card"><div class="agent-catalog">${list.map(([n,p,a])=>`<div class="agent-tile"><strong>${esc(n)}</strong><p>${esc(p)}</p><span>${esc(a)}</span></div>`).join('')}</div></article>`;
  }

  function calendar(){
    const days=['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'];
    return `${head('Calendrier','Échéances, rendez-vous, suivis et relances réunis dans une vue simple.','Organise ma semaine HI MARKETING à partir des priorités actuelles.','Quelles échéances dois-je surveiller ?')}${kpis([[0,'Aujourd’hui'],[0,'Cette semaine'],[0,'Relances'],[0,'RDV']])}<article class="workspace-card"><div class="calendar-grid">${days.map(d=>`<div class="calendar-day"><b>${d}</b><span>Aucun élément planifié</span></div>`).join('')}</div><div class="workspace-note" style="margin-top:12px">Le calendrier reste vide tant qu’aucune échéance réelle n’est synchronisée ou créée.</div></article>`;
  }

  function documents(){
    return `${head('Documents','Devis, propositions, plaquettes, contrats et documents commerciaux au même endroit.','Prépare un nouveau document commercial HI MARKETING.','Montre-moi les documents à mettre à jour.')}${kpis([[0,'Brouillons'],[0,'À valider'],[0,'Envoyés'],[0,'Archivés']])}<article class="workspace-card"><div class="doc-grid"><div class="doc-card"><strong>Proposition commerciale</strong><small>Offre, bénéfices, livrables</small><button data-workspace-command="Prépare une proposition commerciale HI MARKETING professionnelle.">Créer ↗</button></div><div class="doc-card"><strong>Devis</strong><small>Tarifs, options, conditions</small><button data-workspace-command="Prépare un devis HI MARKETING professionnel.">Créer ↗</button></div><div class="doc-card"><strong>Plaquette</strong><small>Présentation premium de l’offre</small><button data-workspace-command="Prépare une plaquette commerciale HI MARKETING.">Créer ↗</button></div><div class="doc-card"><strong>Contrat</strong><small>Structure à validation A3</small><button data-workspace-command="Prépare un brouillon de contrat HI MARKETING sans le signer.">Préparer ↗</button></div><div class="doc-card"><strong>Rapport</strong><small>Suivi et synthèse</small><button data-workspace-command="Prépare un rapport exécutif HI MARKETING.">Créer ↗</button></div><div class="doc-card"><strong>Autre document</strong><small>Brief libre</small><button data-workspace-command="Aide-moi à créer un document professionnel.">Démarrer ↗</button></div></div></article>`;
  }

  function settings(d,h){
    const stat=(ok,label,value)=>`<div class="status-line"><i class="status-dot-small ${ok?'':'warn'}"></i><strong>${esc(label)}</strong><small>${esc(value)}</small></div>`;
    return `${head('Paramètres','État technique, sécurité et règles d’exploitation de HI OS.','Fais un diagnostic complet de la configuration HI OS.','Explique-moi les paramètres qui nécessitent mon attention.')}${kpis([[h.version||'—','Version'],[d.agentRuns,'Runs / 24h'],[h.adminConfigured?'Oui':'Non','Admin'],[h.tenantIsolation?'Strict':'À vérifier','Isolation']])}<div class="settings-grid"><div class="settings-panel"><h4>Infrastructure</h4>${stat(h.database,'Base de données',h.database?'Connectée':'Indisponible')}${stat(h.gmailConfigured,'Google / Gmail',h.gmailConfigured?'Configuré':'À configurer')}${stat(h.aiConfigured,'Moteur IA',h.aiConfigured?'Clé configurée':'Crédit API à régler')}${stat(h.cvEncryptionConfigured,'Chiffrement',h.cvEncryptionConfigured?'Actif':'À vérifier')}</div><div class="settings-panel"><h4>Sécurité</h4><p>Les actions A3 restent soumises à validation humaine. Les intégrations et documents sensibles sont isolés par tenant et mission. Les secrets ne doivent jamais être exposés dans l’interface.</p><div class="workspace-note" style="margin-top:12px">HI OS doit rester utilisable même si un fournisseur externe est temporairement indisponible.</div></div></div>`;
  }

  function fallback(m,d){return `${head(m.name,m.desc,`${m.name}, aide-moi à démarrer avec l’action la plus utile.`)}${kpis([[d.clients,'Clients'],[d.missions,'Missions'],[d.agentRuns,'Runs agents'],[d.interviews,'Priorités']])}<article class="workspace-card">${empty('Module prêt','La structure est en place. Utilise HI Assistant pour lancer la première opération réelle.',`${m.name}, lance la première opération utile.`)}</article>`;}

  window.HIOSWorkspace={render};
})();